### ISSUE TITLE
RFC: Integration of Autotune with React

### ISSUE THREAD

**Issue by prichodko** [dvdsgl/gatsby-autotune-demo#1]
Yo! I am opening an issue to clarify a few things and propose further steps to make Autotune working with React according to current best practices.

## Gatsby
First of all Gatsby is a static-site generator. It means that it builds all the content (specified by GraphQL queries) during **build-time**. This is why `onClientEntry` can't return Promise (everything is already build).

The reason why it's working locally for you is because while in development mode, the server will watch for changes to files and rebuild/update accordingly. In production, this is a static site and content is only updated when you do a fresh build and deploy to your host.

There are ways how to build dynamic parts it Gatsby ([link](https://www.gatsbyjs.org/docs/building-apps-with-gatsby/)), but this is not what you want to do, because you are not leveraging the benefits of Gatsby and there is almost no difference comparing to regular client-rendered React app.

Correct integration with Gatsby would be to build custom plugin (e.g. `gatsby-source-autotune`) - [guide](https://www.gatsbyjs.org/docs/create-source-plugin/) to provide data layer for the app. Example - [link](https://www.gatsbyjs.org/packages/gatsby-source-contentful/).

---

However, at the beginning I would focus on integration with pure React (since it's the widest use-case), then with other frameworks (which has some specific implementational details).

## Bindings
Although I couldn't find it on GitHub, I suppose you have an Autotune JavaScript library. It's a common practice to write bindings to a library (e.g. `react-autotune`), which implements known API for React users.

### Initialization
From what I understood in README Autotune should be initialised before rendering? If yes in React it could be done as simple as:

```js
// top level component - e.g. App.js

class App extends Component {
  state = {
    isInitialized: false
  }

  async componentDidMount() {
    await autotune.init(KEY)
    this.setState({ isInitialized: true })
  }

  componentWillUnmount() {
    autotune.destroy()
  }
 
  render() {
    const { isInitialized } = this.state

    if (!isInitialized) {
      return <Loading />
    }

    return (
      // app
    )
  }
}

export default App
```

this is how it could be done using vanilla Autotune library, but this is really not the best DX. So in React bindings you could create something like 

```js
import autotune from 'autotune'
import { AutotuneProvider } from 'react-autotune'

const client = autotune.createClient(KEY)

class App extends Component {
  render() {
    return (
      <AutotuneProvider client={client}>
        // app
      </AutotuneProvider>
    )
  }
}

// Provider
class AutotuneProvider extends Component {
  // perform initilization

  render() {
    const { isInitilized } = this.state
    const { children } = this.props
    
    return isInitilized ? children : null
  }
}
```
keep in mind that this is really raw pseudo-code and I would do more things in actual implementation.

### Providing data to components
In React you can provide dynamic data in a declarative and implementation agnostic way using either render-props or higher-order components.

```js
import { Variant, withVariant } from "react-autotune"

const variants = {
  bgColor: ["#8e44ad", "#2980b9", "#2c3e50", "#2ecc71"],
  action: ["Sign In", "Log In", "Create Account"]
}

const LoginButton = () => (
  <Variant oneOf={variants}>
    {({ bgColor, action }) => (
      <button
        type="submit"
        style={{ backgroundColor: bgColor }}
      >
        {action}
      </button>
    )}
  </Variant>
)

// using higher-order component
withVariant(variants)(SomeComponent) // SomeComponent will receive it thru props
```

This is the rough idea. I will happily help with final specification.

**Comment by dvdsgl** [comment]
I see, thank you this is excellent. I will refer to this when I work on `react-autotune`.

Autotune is now available here: https://github.com/quicktype/autotune
